### ISSUE TITLE
Site creation not allowed in Alfresco 4.2.f

### ISSUE THREAD

**Issue by angelborroy** [bmejias/alfresco-shell-tools#2]
I was struggling with this script (https://github.com/bmejias/alfresco-shell-tools/blob/master/bin/alfCreateSite.sh) in order to get it working on Alfresco 4.2.f without success. Any idea to give me a light?

Thanks

**Comment by hi-ko** [comment]
I get
`curl: (3) <url> malformed`
I will check the right syntax to be used for 4.2.f later today.
I think we need to create version specific branches to support the changes in the webscripts done version by version and we need a concept how to test everything automatically.

**Comment by angelborroy** [comment]
I think syntax is not the problem:

```
$ ./alfCreateSite.sh -v NewSite
connection params:
  user: admin
  endpoint: http://127.0.0.1:8080/alfresco
  curl opts: -s -S -k -f -v
  site title: NewSite
  site desc:
  site visibility: PUBLIC
  site preset: site-dashboard
  site short name:
* Hostname was NOT found in DNS cache
* Could not resolve host: Path=
* Closing connection 0
curl: (6) Could not resolve host: Path=
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#1)
> POST /share/service/modules/create-site HTTP/1.1
> User-Agent: curl/7.37.1
> Host: 127.0.0.1:8080
> Accept: */*
> Cookie: JSESSIONID=5CF2AD79A87EA5D2DD8301855F379272;
> Content-Type: application/json
> Content-Length: 120
>
* upload completely sent off: 120 out of 120 bytes
< HTTP/1.1 200 OK
* Server Apache-Coyote/1.1 is not blacklisted
< Server: Apache-Coyote/1.1
< Set-Cookie: Alfresco-CSRFToken=wiTkiqjcyXevMeW3HX0jZ8MJ%2bV3K00O6g8K58mfcmdM%3d; Expires=Tue, 09-Dec-2014 15:26:08 GMT; Path=/share
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< Content-Language: es-ES
< Content-Length: 0
< Date: Tue, 02 Dec 2014 15:26:08 GMT
<
* Connection #1 to host 127.0.0.1 left intact
```

curl: (6) Could not resolve host: Path=

**Comment by angelborroy** [comment]
This info could be valuable:

https://issues.alfresco.com/jira/browse/MNT-11706

**Comment by billerby** [comment]
Too bad that there is no solution in the jira, only "fixed". I'm facing the same stuff for the moment trying to create multiple sites programatically from java. Asked on stackoverflow and Dave Webster answered, but I cant get it to work. http://stackoverflow.com/questions/27251706/how-to-create-site-in-share-programmatically

He does not state how to obtain the Alfresco-CSRFToken. Also found some clues in the following forum thread. In this thread three rest-calls seems to be made for a succesful site creation. Tried to understand all steps but failed with an possble CSRF-attack. 

https://forums.alfresco.com/forum/developer-discussions/alfresco-api/authentication-woes-share-rest-api-09222014-1204

**Comment by fsckawk** [comment]
I have patched alfCreateSite.sh and alfToolsLib.sh so it will work with Alfresco 5.0.c with default (enabled) CSRF protection.
You can find it at https://webdiis.unizar.es/~spd/tmp/afs.tgz
Should I submit the patches here?

**Comment by fsckawk** [comment]
I have updated the patched files at https://webdiis.unizar.es/~spd/tmp/afs.tgz
List of changes:
- bin/alfCreateSite.sh

```
# Make it work with CSRF enabled Alfresco 5.x

# spd: fixed bug: supplied short name is ignored
# spd: visibility defaults to "private"
# spd: add some cookies (alfLogin, alfUsername3, others supplied by server)
# spd: read and use Alfresco-CSRFToken
# spd: add "Referer" and "Origin" HTTTP headers
# spd: add "isPublic" attribute to JSON
# spd: cosmetic changes in source code (split some long lines)
```
- bin/alfToolsLib.sh

```
#
# fixes in __get_share_session_id
#
```

**Comment by bmejias** [comment]
Hi José (fsckawk)

My apologies for this very late reply. I should have treated right away, but then I lost track of it. I'm going to apply your asap. I still need to test whether it breaks backwards compatibility with the previous versions of Alfresco.

cheers
Boriss

**Comment by jayasank** [comment]
Hello,

I am facing an issue while executing /usr/local/share/alfresco-shell-tools/bin/alfCreateSite.sh in alfresco Community - 5.0.0

Getting error as below
./alfCreateSite.sh 'Mynewsite'
./alfCreateSite.sh: line 104: jshon: command not found
curl: (6) Couldn't resolve host 'Path='

Anyone please help me to resolve the issue.

Regards,
Arya

**Comment by marsbard** [comment]
You need to install jshon http://kmkeen.com/jshon/

**Comment by jayasank** [comment]
Thanks marsbard,
I have got jshon.tar.gz file and inside the unzipped directory, I have got below listed 3 files
jshon.1
jshon.c
Makefile

How can I proceed on the installation since I am not getting any installation instructions from anywhere?
And I am new to this alfresco, so could you please help!!

Thanks in Advance,
Arya

**Comment by hi-ko** [comment]
Hi Arya, have you followed this guide?
https://code.google.com/archive/p/alfresco-shell-tools/wikis/InstallationGuide.wiki

**Comment by jayasank** [comment]
Hello,

We have installed jshon and run make file.
Still we are getting the same error. As we can see in alfCreateSite.sh script , there is env variables ALF_JSHON . So do we have to set that as home folder of jshon like /usr/local/share

Thanks and Regards,
Arya

**Comment by marsbard** [comment]
See if your package manager provides it. For example, ubuntu does: http://packages.ubuntu.com/wily/jshon so if you were on ubuntu you could just do `apt-get install jshon`

**Comment by jayasank** [comment]
Hi,

I am doing in Linux and the command  apt-get install jshon  is not working in Linux. I found that the same command has been provided to install jshon in Linux.
error getting is - sudo: apt-get: command not found

How can I proceed?

Regards,
Arya

**Comment by hi-ko** [comment]
Hi  Arya,
please make yourself familiar with your operation system how to install software in general and if you have an issue specific to alfresco-shell-tools you can create an issue here

**Comment by jayasank** [comment]
This was not the issue with my familiarity of operation system. Make sure your script is proper. we have modified alfCreateSite.sh script and now its working properly.
